// Code generated by go-genconstructor; DO NOT EDIT.

package slack

import (
	"github.com/nlopes/slack"
	"github.com/opensaasstudio/meerkat/application"
	"github.com/opensaasstudio/meerkat/domain"
	"go.uber.org/zap"
)

func NewAnsweringHandler(
	slackClient *slack.Client,
	usecase application.AnsweringUsecase,
) AnsweringHandler {
	return AnsweringHandler{
		slackClient: slackClient,
		usecase:     usecase,
	}
}

func NewCreatingAnswererHandler(
	slackClient *slack.Client,
	usecase application.CreatingAnswererUsecase,
) CreatingAnswererHandler {
	return CreatingAnswererHandler{
		slackClient: slackClient,
		usecase:     usecase,
	}
}

func NewHTTPHandler(
	slackVerificationToken string,
	logger *zap.Logger,
	questionnaireSearcher domain.QuestionnaireSearcher,
	answererSearcher domain.AnswererSearcher,
	editingQuestionnaireHandler EditingQuestionnaireHandler,
	creatingAnswererHandler CreatingAnswererHandler,
	addingAnswererHandler AddingAnswererHandler,
	answeringHandler AnsweringHandler,
	paramStore ParamStore,
) HTTPHandler {
	return HTTPHandler{
		slackVerificationToken:      slackVerificationToken,
		logger:                      logger,
		questionnaireSearcher:       questionnaireSearcher,
		answererSearcher:            answererSearcher,
		editingQuestionnaireHandler: editingQuestionnaireHandler,
		creatingAnswererHandler:     creatingAnswererHandler,
		addingAnswererHandler:       addingAnswererHandler,
		answeringHandler:            answeringHandler,
		paramStore:                  paramStore,
	}
}

func NewPoster(
	slackClient *slack.Client,
) Poster {
	return Poster{
		slackClient: slackClient,
	}
}

func NewAddingAnswererHandler(
	slackClient *slack.Client,
	usecase application.AddingAnswererUsecase,
) AddingAnswererHandler {
	return AddingAnswererHandler{
		slackClient: slackClient,
		usecase:     usecase,
	}
}

func NewEditingQuestionnaireHandler(
	slackClient *slack.Client,
	creatingQuestionnaireUsecase application.CreatingQuestionnaireUsecase,
	updatingQuestionnaireUsecase application.UpdatingQuestionnaireUsecase,
) EditingQuestionnaireHandler {
	return EditingQuestionnaireHandler{
		slackClient:                  slackClient,
		creatingQuestionnaireUsecase: creatingQuestionnaireUsecase,
		updatingQuestionnaireUsecase: updatingQuestionnaireUsecase,
	}
}
