[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.11.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.19.40"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.3.1"

[[constraint]]
  name = "github.com/guregu/dynamo"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/hori-ryota/zaperr"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/nlopes/slack"

[[constraint]]
  name = "github.com/oklog/ulid"
  version = "2.0.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.1"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "gopkg.in/guregu/null.v3"
  version = "3.4.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true
  non-go = true
